name: anio
description: Anio is a library that complements `dart:io` to make it much easier to access, store, and process your data.
version: 1.0.1
homepage: https://github.com/sososdk/io/tree/master/anio

environment:
  sdk: '>=2.18.4 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  file: '>=6.1.2 <7.0.0'
