name: anio
description: Anio is a library that complements `dart:io` to make it much easier to access, store, and process your data.
version: 2.0.10
homepage: https://github.com/sososdk/io/tree/master/anio

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  meta: '>=1.7.0 <2.0.0'

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  convert: ^3.1.2
  file: '>=7.0.0 <8.0.0'
