name: anio
description: Anio is a library that complements `dart:io` to make it much easier to access, store, and process your data.
version: 1.1.0
homepage: https://github.com/sososdk/io/tree/master/anio

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  synchronizer: ^1.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  file: '>=7.0.0 <8.0.0'
