name: disk_cache_manager
description: Disk cache manager for dart.
version: 1.0.4
homepage: https://github.com/sososdk/io/tree/master/disk_cache_manager

environment:
  sdk: '>=2.16.2 <4.0.0'

dependencies:
  crypto: '>=3.0.2 <4.0.0'
  pool: '>=1.5.0 <2.0.0'
  disk_cache: ^1.0.6
  file_system: ^1.0.2
  anio: ^1.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
