name: anzip
description: A dart library for zip files / streams.
version: 2.0.5
repository: https://github.com/sososdk/io/anzip

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0
  path: '>=1.8.0 <2.0.0'
  convert: '>=3.1.1 <4.0.0'
  collection: '>=1.18.0 <2.0.0'
  pointycastle: '>=3.7.4 <4.0.0'
  anio: ^2.0.9
  file_system: ^2.0.8

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.14
