name: anzip
description: A dart library for zip files / streams.
version: 2.0.6
repository: https://github.com/sososdk/io/anzip

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  anio: ^2.0.10
  file_system: ^2.0.9
  meta: '>=1.7.0 <2.0.0'
  path: '>=1.8.0 <2.0.0'
  convert: '>=3.1.1 <4.0.0'
  collection: '>=1.18.0 <2.0.0'
  pointycastle: '>=3.7.4 <4.0.0'

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
