name: anzip
description: A dart library for zip files / streams.
version: 1.0.3
repository: https://github.com/sososdk/io/anzip

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  path: '>=1.8.0 <2.0.0'
  collection: '>=1.18.0 <2.0.0'
  pointycastle: '>=3.7.4 <4.0.0'
  anio: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

  file_system: ^1.0.2
