name: disk_cache
description: Disk lru cache for dart.
version: 1.0.10
homepage: https://github.com/sososdk/io/tree/master/disk_cache

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  logging: '>=1.0.2 <2.0.0'
  path: '>=1.8.0 <2.0.0'
  meta: '>=1.7.0 <2.0.0'
  anio: ^2.0.5
  file_system: ^2.0.4
  synchronizer: ^1.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.14
