name: disk_lru_cache
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  logging: '>=1.0.2 <2.0.0'
  path: '>=1.8.0 <2.0.0'
  meta: '>=1.7.0 <2.0.0'
  file_system: any

dependency_overrides: 
  file_system:
    path: ../file_system
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
