name: synchronizer
description: Lock mechanism to prevent concurrent access to asynchronous code.
version: 1.0.0
homepage: https://github.com/sososdk/io/tree/master/synchronizer

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
