name: file_system
description: A generic file system abstraction for Dart.
version: 1.0.2
homepage: https://github.com/sososdk/io/tree/master/file_system

environment:
  sdk: '>=2.16.2 <4.0.0'

dependencies:
  file: '>=6.1.2 <7.0.0'
  path: '>=1.8.0 <2.0.0'
  anio: ^1.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
