name: file_system
description: A generic file system abstraction for Dart.
version: 2.0.7
homepage: https://github.com/sososdk/io/tree/master/file_system

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  file: '>=7.0.0 <8.0.0'
  path: '>=1.8.0 <2.0.0'
  anio: ^2.0.8

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.14
