name: file_system
description: A generic file system abstraction for Dart.
version: 1.0.1
homepage: https://github.com/sososdk/io/tree/master/file_system

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  file: '>=6.1.2 <7.0.0'
  path: '>=1.8.0 <2.0.0'
  anio: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
